import {test,expect} from '@playwright/test';
test('real application library, draft setup, evidence, export and narrow layout',async({page,request})=>{
 const proposition=`Synthetic browser check ${Date.now()}: libraries should extend weekend hours.`;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{name:'Room for a second opinion.'})).toBeVisible();
 await page.screenshot({path:'../docs/screenshots/library-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'New debate',exact:true}).last().click();
 await page.getByLabel('State a proposition').fill(proposition);
 await page.getByLabel('Completed turns').fill('4');
 await page.screenshot({path:'../docs/screenshots/setup-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Create debate',exact:false}).click();
 await expect(page.getByRole('heading',{name:'Your subject, made clear.'})).toBeVisible();
 await page.getByLabel('Evidence text').fill('Synthetic evidence: 40 survey participants requested weekend access.');
 await page.getByRole('button',{name:'Add text',exact:false}).click();
 await expect(page.getByRole('button',{name:/pasted-text.txt/})).toBeVisible();
 await page.getByRole('button',{name:/pasted-text.txt/}).click();
 await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByText('Run settings & allowances').click();await page.getByLabel('Total turns',{exact:true}).fill('6');await page.getByRole('button',{name:'Update turn count'}).click();
 await expect(page.getByText('/ 6',{exact:true})).toBeVisible();
 await expect(page.getByText('SESSION TOKENS USED',{exact:true})).toBeVisible();
 await page.getByLabel('Maximum automatic context',{exact:true}).selectOption('24576');
 await page.getByRole('button',{name:'Update context ceiling'}).click();
 await expect(page.getByText(/Automatic context ceiling: 24,576/)).toBeVisible();
 await page.screenshot({path:'../docs/screenshots/chamber-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../docs/screenshots/chamber-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Evidence & claims'}).click();await expect(page.getByRole('button',{name:/pasted-text.txt/})).toBeVisible();
 expect(errors).toEqual([]);
 const sessions=await (await request.get('/api/sessions')).json();
 const created=sessions.find((s:any)=>s.proposition===proposition);
 expect((await (await request.get(`/api/sessions/${created.id}/export?format=json`)).json()).run.settings.turn_limit).toBe(6);
 await request.delete(`/api/sessions/${created.id}`);
});

test('saved real-model verdict, source citation and interrupted-attempt marker',async({page,request})=>{
 const response=await request.get('http://127.0.0.1:8788/api/sessions',{timeout:1500}).catch(()=>null);
 test.skip(!response,'Start the isolated verification preview to review saved real-model results.');
 const sessions=await response!.json();const completed=sessions.find((s:any)=>s.state==='COMPLETED');
 expect(completed).toBeTruthy();
 await page.goto('http://127.0.0.1:8788');
 await page.getByRole('button',{name:new RegExp(completed.proposition.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).first().click();
 await expect(page.getByRole('heading',{name:completed.outcome,exact:true})).toBeVisible();
 await expect(page.getByText('An interrupted attempt was excluded from completed history and judgment. Resume regenerates the pending turn.')).toBeVisible();
 await page.getByRole('heading',{name:completed.outcome,exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'../docs/screenshots/real-verdict-desktop.png'});
 await page.locator('.verdict .citation-list button').first().click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Extracted passages'})).toBeVisible();
 await page.screenshot({path:'../docs/screenshots/real-source-inspector.png'});
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('heading',{name:completed.outcome,exact:true}).scrollIntoViewIfNeeded();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../docs/screenshots/real-verdict-mobile.png'});
});

test('local speech model configured and video citations seek to the transcript timestamp',async({page,request})=>{
 const health=await (await request.get('/api/health')).json();
 test.skip(!health.transcription_configured,'Requires the explicitly approved local transcription model.');
 const response=await request.get('http://127.0.0.1:8788/api/sessions',{timeout:1500}).catch(()=>null);
 test.skip(!response,'Start the isolated verification preview for the media fixture.');
 const sessions=await response!.json();
 test.skip(!sessions.some((s:any)=>s.proposition==='Synthetic audio/video ingestion verification'),'Run the explicit local media-admission probe first.');
 await page.goto('http://127.0.0.1:8788');
 await page.getByRole('button',{name:/Synthetic audio\/video ingestion verification/}).first().click();
 await page.getByRole('button',{name:/synthetic-video.mp4 admitted/}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.locator('video')).toBeVisible();
 await page.getByRole('button',{name:'Seek to 7s',exact:true}).click();
 await expect.poll(()=>page.locator('video').evaluate((v:any)=>v.currentTime)).toBeGreaterThanOrEqual(7.4);
 await page.screenshot({path:'../docs/screenshots/media-inspector.png'});
 await page.keyboard.press('Escape');
});
