import {test,expect} from '@playwright/test';
test('guided preparation: questions, editable positions, approval, fork and narrow layout',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'New debate',exact:true}).last().click();
 await page.getByLabel('State a proposition').fill('Synthetic preparation UI check');
 await page.getByLabel('Completed turns').fill('4');await page.getByRole('button',{name:'Create debate'}).click();
 await expect(page.getByRole('heading',{name:'Your subject, made clear.'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Start',exact:true})).toHaveCount(0);
 await page.getByLabel('Evidence text').fill('Fictional trial budget: $240. Demand is unmeasured.');await page.getByRole('button',{name:'Add text'}).click();
 await page.getByRole('button',{name:'Analyze inputs with Charlie'}).click();
 await expect(page.getByRole('heading',{name:'Questions for you'})).toBeVisible();
 await page.getByLabel('Answer Charlie').fill('The budget is $240. Compare a trial with measuring demand first.');await page.getByRole('button',{name:'Send to Charlie'}).click();
 await expect(page.getByText('The budget is $240. Compare a trial with measuring demand first.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Review inputs again'})).toBeEnabled();
 await page.getByLabel('Alpha’s position',{exact:true}).fill('Run a four-week trial with a $240 cap');
 await page.getByRole('button',{name:'Save brief edits'}).click();
 await page.getByLabel(/I accept the listed gaps/).check();await page.getByRole('button',{name:'Approve debate brief'}).click();
 await expect(page.getByRole('button',{name:'Start',exact:true})).toBeVisible();
 await page.screenshot({path:'../docs/screenshots/preparation-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'../docs/screenshots/preparation-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Start',exact:true}).click();
 await expect(page.getByRole('heading',{name:'tie',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Revise subject in a new draft'}).click();
 await expect(page.getByRole('heading',{name:'Your subject, made clear.'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Start',exact:true})).toHaveCount(0);
 expect(errors).toEqual([]);
});
test('prepared shortcut supports path and upload, saved copy, and edit invalidation',async({page,request})=>{
 await page.goto('/');await page.getByRole('button',{name:'New debate',exact:true}).last().click();
 await page.getByLabel('Preparation',{exact:true}).selectOption('prepared');
 await page.getByLabel('State a proposition').fill('Shortcut test question');await page.getByLabel('Alpha’s position').fill('Take action');await page.getByLabel('Bravo’s position').fill('Wait');
 await page.getByRole('button',{name:'Create debate'}).click();
 await page.getByRole('button',{name:'Path',exact:true}).click();await expect(page.getByLabel('Local file path')).toBeVisible();
 await page.getByRole('button',{name:'File',exact:true}).click();
 await page.locator('input[type=file]').setInputFiles({name:'source.md',mimeType:'text/markdown',buffer:Buffer.from('Synthetic uploaded source')});
 await expect(page.getByRole('button',{name:/source.md staged/})).toBeVisible();
 await page.getByLabel(/I accept the listed gaps/).check();await page.getByRole('button',{name:'Approve debate brief'}).click();
 await expect(page.getByRole('button',{name:'Start',exact:true})).toBeVisible();
 await page.getByLabel('Debate question',{exact:true}).fill('Revised shortcut question');await page.getByRole('button',{name:'Save brief edits'}).click();
 await expect(page.getByRole('button',{name:'Start',exact:true})).toHaveCount(0);
});
