import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Plus, ArrowLeft, ArrowRight, Play, Pause, RotateCcw, Square, Scale, Files, MessageSquare, ChevronRight, Download, X, AlertCircle, Check, Radio, Settings2, Trash2, Upload, Link, ExternalLink } from 'lucide-react';
import './style.css';
import {PreparationPanel} from './PreparationPanel';
type Settings={execution_policy?:'fixed'|'completion';policy_version?:number;models:Record<string,string>;turn_limit:number;active_minutes:number;ingestion_tokens:number;debate_tokens:number;judgment_tokens:number;context_tokens:number;max_context_tokens:number;output_tokens:number;search_enabled:boolean;search_limit:number};
type Source={id:string;name:string;kind:string;status:string;summary:string|null;error:string|null;hash:string;uncertainty:string[];passages:{id:string;text:string;derived?:boolean;locator:Record<string,any>}[];metadata:Record<string,any>};
type Turn={id:string;speaker:string;phase:string;text:string;claims:{text:string;references:string[];status:string}[];concessions:string[];evidence_version:number;instruction_version:number};
type Run={preparation?:any;debate_started?:boolean;id:string;proposition:string;state:string;phase:string;activity:string;revision:number;settings:Settings;turns:Turn[];sources:Source[];claims:any[];requests:any[];usage:Record<string,number>;usage_unknown:boolean;active_seconds:number;clock_uncertain:boolean;closing_started:boolean;error:string|null;verdict:any;judgment_snapshot:any;instructions:any[];parent_id:string|null;updated:number;attempts:any[];context_versions?:any[];job?:any;request_context?:any};
type Summary={id:string;proposition:string;state:string;updated:number;turn_count:number;outcome:string|null;parent_id:string|null};
const roles=['Alpha','Bravo','Charlie','Judge'];
const active=['PREPARING','RUNNING','INGESTING','JUDGING','PAUSING','STOPPING'];
const terminal=['COMPLETED','CANCELED'];
async function api(path:string,body?:unknown,method?:string):Promise<any>{
 const response=await fetch('/api'+path,{method:method||(body?'POST':'GET'),headers:body instanceof FormData?{}:body?{'Content-Type':'application/json'}:{},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});
 const data=await response.json(); if(!response.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail)); return data;
}
function pretty(s:string){return s.toLowerCase().replaceAll('_',' ')}
function tokenUsage(run:Run){
 const total=Object.values(run.usage).reduce((a,b)=>a+b,0);
 const reserved=(run.job?.input_tokens==null||run.job?.output_tokens==null)?(run.job?.reservation||0):0;
 const uncertain=run.attempts.filter(a=>a.input_tokens==null||a.output_tokens==null).reduce((n,a)=>n+(a.reservation||0),0);
 return {reported:Math.max(0,total-reserved-uncertain),reserved,uncertain};
}
function App(){
 const [list,setList]=useState<Summary[]>([]),[run,setRun]=useState<Run|null>(null),[page,setPage]=useState<'library'|'setup'|'chamber'>('library');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[models,setModels]=useState<any[]>([]),[defaults,setDefaults]=useState<Settings|null>(null),[live,setLive]=useState<any>(null);
 const [tab,setTab]=useState<'evidence'|'claims'>('evidence'),[inspected,setInspected]=useState<Source|null>(null),[locator,setLocator]=useState<any>(null),[drawer,setDrawer]=useState(false),[follow,setFollow]=useState(true),[turnTotal,setTurnTotal]=useState(12);
 const end=useRef<HTMLDivElement>(null); const runRef=useRef<Run|null>(null); runRef.current=run;
 async function refreshList(){setList(await api('/sessions'))}
 useEffect(()=>{refreshList().catch(e=>setError(e.message));api('/defaults').then(setDefaults).catch(e=>setError(e.message));api('/models').then(x=>setModels(x.models)).catch(e=>setError(e.message))},[]);
 useEffect(()=>{
  if(!run?.id||page!=='chamber')return;
  const id=run.id; const events=new EventSource(`/api/sessions/${id}/events`); let mounted=true; let refreshTimer:ReturnType<typeof setTimeout>|null=null;
  events.addEventListener('state',()=>{if(refreshTimer)return;refreshTimer=setTimeout(()=>{refreshTimer=null;api(`/sessions/${id}`).then(s=>{if(mounted)setRun(current=>!current||current.id!==s.id||s.revision>=current.revision?s:current)}).catch(e=>setError(e.message))},60)});
  events.addEventListener('public',(e:any)=>{if(mounted)setLive(JSON.parse(e.data))});
  return()=>{mounted=false;if(refreshTimer)clearTimeout(refreshTimer);events.close();setLive(null)};
 },[run?.id,page]);
 useEffect(()=>{if(follow&&(live||run?.turns.length))end.current?.scrollIntoView({behavior:'smooth',block:'end'})},[live?.text,run?.turns.length,follow]);
 useEffect(()=>{if(run)setTurnTotal(run.settings.turn_limit)},[run?.id,run?.settings.turn_limit]);
 useEffect(()=>{if(page!=='chamber')return;const wheel=(e:WheelEvent)=>{if(e.deltaY<0)setFollow(false)};const key=(e:KeyboardEvent)=>{if(['PageUp','Home','ArrowUp'].includes(e.key))setFollow(false)};window.addEventListener('wheel',wheel,{passive:true});window.addEventListener('keydown',key);return()=>{window.removeEventListener('wheel',wheel);window.removeEventListener('keydown',key)}},[page]);
 async function execute(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 async function open(id:string){await execute(async()=>{setRun(await api('/sessions/'+id));setPage('chamber');setFollow(true)})}
 async function command(command:string){if(!run)return;await execute(async()=>{
  const current:Run=await api('/sessions/'+run.id);
  const result=await api(`/sessions/${run.id}/commands`,{command,expected_revision:current.revision,idempotency_key:crypto.randomUUID()});setRun(result);
 })}
 function inspectReference(ref:string){
  if(ref.startsWith('T')){document.getElementById(ref)?.scrollIntoView({behavior:'smooth'});setFollow(false);return}
  const source=run?.sources.find(s=>s.id===ref.split(':')[0]);if(source){setInspected(source);setLocator(source.passages.find(p=>p.id===ref)?.locator||null)}
 }
 async function remove(){if(!run||!window.confirm('Delete this saved session and its unshared evidence files? This cannot be undone.'))return;await execute(async()=>{await api('/sessions/'+run.id,undefined,'DELETE');setRun(null);setPage('library');await refreshList()})}
 const preparing=!!run?.preparation&&!run?.debate_started;
 async function preparationAction(action:string,extra:any={}){if(!run)return false;return execute(async()=>{const result=await api(`/sessions/${run.id}/preparation`,{action,expected_revision:run.revision,...extra});setRun(await api('/sessions/'+result.id))})}
 const pending=run?.requests.find(r=>r.status==='pending');
 const editable=!!run&&['DRAFT','PAUSED','AWAITING_USER','FAILED_RECOVERABLE'].includes(run.state)&&!run.judgment_snapshot;
 return <div className="app-shell">
  <aside className="rail"><button className="brand" onClick={()=>{setPage('library');refreshList()}} aria-label="Debate Lab library"><BookOpen size={24}/></button><span className="rail-line"/><button className={page==='library'?'rail-button selected':'rail-button'} aria-label="Session library" onClick={()=>{setPage('library');refreshList()}}><Files size={20}/></button><button className="rail-button" aria-label="New debate" onClick={()=>setPage('setup')}><Plus size={21}/></button><span className="rail-bottom">LOCAL</span></aside>
  <div className="workspace"><header className="topbar"><div className="wordmark">Debate <em>Lab</em><span className="wordmark-divider"/><span className="top-subtitle">A place for considered arguments</span></div><span className="local-badge"><span/> Local inference & storage</span></header>
  {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
  {page==='library'&&<main className="library"><div className="eyebrow">YOUR RESEARCH SPACE</div><div className="page-heading"><div><h1>Room for a second opinion.</h1><p>Put a proposition to the test. Follow the evidence. Keep the conversation.</p></div><button className="primary" onClick={()=>setPage('setup')}><Plus size={17}/> New debate</button></div>
   <div className="intro-grid"><div className="intro-card"><span className="step-number">01</span><h3>Frame the question</h3><p>Charlie interprets your inputs and helps you choose the question and positions.</p></div><div className="intro-card"><span className="step-number">02</span><h3>Let the arguments meet</h3><p>Watch the exchange. Pause to add context, or ask for judgment when you’re ready.</p></div><div className="intro-card"><span className="step-number">03</span><h3>Understand the verdict</h3><p>Inspect the reasoning, sources, concessions, and what remains uncertain.</p></div></div>
   <div className="section-heading"><h2>Your sessions <span>{list.length}</span></h2><span>Saved on this computer</span></div>
   {list.length===0?<div className="empty-library"><div className="empty-icon"><MessageSquare size={30}/></div><h2>Your first question belongs here.</h2><p>Start with an idea you want to examine.<br/>Evidence is welcome, but not required.</p><button className="text-button" onClick={()=>setPage('setup')}>Create a debate <ArrowRight size={16}/></button></div>:<div className="session-list">{list.map(s=><button className="session-row" key={s.id} onClick={()=>open(s.id)}><div className="session-icon"><MessageSquare size={21}/></div><div className="session-description"><h3>{s.proposition}</h3><p>{s.turn_count} completed turns · {new Date(s.updated*1000).toLocaleDateString()}{s.parent_id?' · Restarted run':''}</p></div><span className={'status '+s.state.toLowerCase()}>{s.outcome||pretty(s.state)}</span><ChevronRight size={18}/></button>)}</div>}
   <footer className="library-footer"><span>Four roles. Shared evidence. Your judgment.</span><span>Model agreement is not proof.</span></footer>
  </main>}
  {page==='setup'&&defaults&&<Setup defaults={defaults} models={models} busy={busy} onBack={()=>setPage('library')} onCreate={data=>execute(async()=>{const s=await api('/sessions',data);setRun(s);setPage('chamber');await refreshList()})} onDefaults={settings=>execute(async()=>{await api('/defaults',settings,'PUT');setDefaults(settings)})}/>}
  {page==='chamber'&&run&&<main className="chamber"><div className="chamber-heading"><button className="back-link" onClick={()=>{setPage('library');refreshList()}}><ArrowLeft size={15}/> Sessions</button><div className="eyebrow">THE DEBATE CHAMBER</div><h1>{run.proposition||"Prepare a new subject"}</h1><div className="run-metadata"><span className={'status '+run.state.toLowerCase()}>{pretty(run.state)}</span><span aria-live="polite">{run.activity}</span><span className="checkpoint"><Check size={13}/> Checkpoint {run.revision}</span></div></div>
   <div className="metrics"><div><span>COMPLETED TURNS</span><strong>{run.turns.length}<small> / {run.settings.turn_limit}</small></strong></div><div><span>ACTIVE TIME</span><strong>{Math.floor(run.active_seconds/60)}:{Math.floor(run.active_seconds%60).toString().padStart(2,'0')}<small>{run.settings.execution_policy==='completion'?' · completion priority':` / ${run.settings.active_minutes} min`}{run.clock_uncertain?' · uncertain interval':''}</small></strong></div><div><span>SESSION TOKENS USED</span><strong>{tokenUsage(run).reported.toLocaleString()}<small> reported</small></strong><small>Current reservation: {tokenUsage(run).reserved.toLocaleString()}</small>{tokenUsage(run).uncertain>0&&<small>Retained estimates: {tokenUsage(run).uncertain.toLocaleString()}</small>}<small>Latest request context: {run.request_context ? `${run.request_context.estimated_input.toLocaleString()} input + ${run.request_context.output_allowance.toLocaleString()} reply / ${run.request_context.capacity.toLocaleString()} · ${run.request_context.method}${run.request_context.expanded?' · expanded':''}`:'Not yet prepared'}</small></div><button className="mobile-panel" onClick={()=>setDrawer(!drawer)}><Files size={17}/> Evidence & claims</button></div>
   {run.error&&<div className="run-error"><AlertCircle size={19}/><div><strong>Attention needed</strong><p>{run.error}</p></div></div>}
   {!preparing&&<button className="secondary" disabled={busy} onClick={()=>preparationAction("fork")}>Revise subject in a new draft</button>}
   {pending&&<RequestPanel request={pending} busy={busy} onAnswer={(choice,text)=>execute(async()=>{setRun(await api(`/sessions/${run.id}/information-requests/${pending.id}/response`,{choice,text}))})}/>}
   <div className="chamber-grid"><section className="transcript"><div className="transcript-header"><h2>The exchange</h2><button className={follow?'small-button live-on':'small-button'} onClick={()=>setFollow(!follow)}><Radio size={13}/>{follow?'Following live':'Follow live'}</button></div>
    {preparing&&<PreparationPanel key={run.id} run={run} busy={busy} act={preparationAction}/>}
    {!preparing&&!run.turns.length&&!live&&<div className="waiting"><Scale size={32}/><h2>{run.state==='DRAFT'?'Set the table.':'Waiting for the next argument.'}</h2><p>{run.state==='DRAFT'?'Add your inputs, review the subject, then start when ready. Both debaters receive the same approved record.':'Completed arguments will appear here. Interrupted work is excluded from judgment.'}</p>{run.state==='DRAFT'&&(!preparing||run.preparation?.approval)&&<button className="primary" disabled={busy} onClick={()=>command('start')}><Play size={16}/> Begin debate</button>}</div>}
    {run.turns.map(t=><article id={t.id} className={'turn role-'+t.speaker.toLowerCase()} key={t.id}><div className="turn-heading"><span className="avatar">{t.speaker[0]}</span><strong>{t.speaker}</strong><span>{t.phase}</span><small>{t.id}</small></div><div className="argument">{t.text}</div>{t.claims.some(c=>c.references.length>0)&&<div className="citation-list">{[...new Set(t.claims.flatMap(c=>c.references))].map(ref=><button key={ref} onClick={()=>inspectReference(ref)}><BookOpen size={12}/>{ref}</button>)}</div>}{t.concessions.length>0&&<div className="concessions">Concessions: {t.concessions.join('; ')}</div>}<div className="turn-foot">Evidence v{t.evidence_version} · Instructions v{t.instruction_version} · Claims require verification</div></article>)}
    {live&&<article className={'turn streaming role-'+live.role.toLowerCase()}><div className="turn-heading"><span className="avatar">{live.role[0]}</span><strong>{live.role}</strong><span>In progress · not saved as a turn</span><span className="pulse"/></div><div className="argument">{live.text||'Preparing a response…'}</div></article>}
    {run.attempts?.some(a=>a.status==='interrupted')&&<p className="interruption-note">An interrupted attempt was excluded from completed history and judgment. Resume regenerates the pending turn.</p>}
    {run.verdict&&<VerdictPanel verdict={run.verdict} onReference={inspectReference}/>}
    <div ref={end}/>
   </section><aside className={'context-panel '+(drawer?'drawer-open':'')}><div className="panel-tabs"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}><Files size={15}/> Evidence <span>{run.sources.length}</span></button><button className={tab==='claims'?'active':''} onClick={()=>setTab('claims')}><MessageSquare size={15}/> Claims <span>{run.claims.length}</span></button></div>
    {tab==='evidence'?<><p className="panel-note">One shared record for every role. Admission means processed, not proven true.</p>{run.sources.map(src=><div className="source-card" key={src.id}><button onClick={()=>{setInspected(src);setLocator(null)}}><span className="source-type">{src.kind.toUpperCase()}</span><strong>{src.name}</strong><span className={'source-status '+src.status}>{src.status}</span></button>{src.error&&<p className="source-error">{src.error}</p>}{editable&&src.status!=='admitted'&&src.status!=='excluded'&&<button className="text-button small" onClick={()=>execute(async()=>{setRun(await api(`/sessions/${run.id}/evidence/${src.id}/exclude`,{}))})}>Exclude this source</button>}</div>)}{!run.sources.length&&<div className="small-empty"><BookOpen size={25}/><p>No evidence added.<br/>Unsupported factual claims remain unverified.</p></div>}{editable&&<EvidenceForm preparing={!!run.preparation} busy={busy} add={(kind,body)=>execute(async()=>{setRun(await api(`/sessions/${run.id}/evidence${kind?'/'+kind:''}`,body))})}/>}<div className="panel-divider"/><h3 className="panel-heading">Shared instructions</h3>{run.instructions.map((i:any)=><p className="instruction" key={i.version}><span>v{i.version}</span>{i.text}</p>)}{editable&&<InstructionForm busy={busy} onAdd={text=>execute(async()=>{setRun(await api(`/sessions/${run.id}/instructions`,{text}))})}/>}</>:<><p className="panel-note">Agent assessments, not independent fact checks. A citation may resolve without supporting the claim.</p>{run.claims.map((c:any,i:number)=><div className="claim-card" key={i}><span className="claim-status">{c.status}</span><p>{c.text}</p><button className="text-button small" onClick={()=>inspectReference(c.turn_id)}>{c.turn_id} <ArrowRight size={12}/></button>{c.references.map((r:string)=><button className="reference" key={r} onClick={()=>inspectReference(r)}>{r}</button>)}</div>)}{!run.claims.length&&<p className="small-empty">Claims appear after a completed turn.</p>}</>}
    <details className="run-settings"><summary><Settings2 size={14}/> Run settings & allowances</summary>{roles.map(role=><p key={role}><strong>{role}</strong><span>{run.settings.models[role]}</span></p>)}<p>Ingestion: {run.usage.ingestion.toLocaleString()} / {run.settings.ingestion_tokens.toLocaleString()}</p><p>Debate: {run.usage.debate.toLocaleString()} / {run.settings.debate_tokens.toLocaleString()}</p><p>Judgment: {run.usage.judgment.toLocaleString()} / {run.settings.judgment_tokens.toLocaleString()}</p><p>Automatic context ceiling: {(run.settings.max_context_tokens??32768).toLocaleString()}. Expansion uses only locally tested capacities. Estimates and summaries can be imperfect.</p>{['DRAFT','PAUSED','FAILED_RECOVERABLE'].includes(run.state)&&<form onSubmit={e=>{e.preventDefault();const value=Number(new FormData(e.currentTarget).get('maximum'));execute(async()=>{setRun(await api(`/sessions/${run.id}/context-settings`,{max_context_tokens:value,expected_revision:run.revision},'PATCH'))})}}><label>Maximum automatic context<select aria-label="Maximum automatic context" name="maximum" key={run.settings.max_context_tokens} defaultValue={run.settings.max_context_tokens??32768}>{[16384,24576,32768,65536,131072].filter(n=>n>=run.settings.context_tokens).map(n=><option key={n} value={n}>{n.toLocaleString()}</option>)}</select></label><button className="secondary" disabled={busy}>Update context ceiling</button></form>}{!!run.context_versions?.length&&<p>Context used {run.context_versions.length} recorded summary/excerpt versions. Full sources and turns remain available; exports retain the derivation records.</p>}<p>Policy: {run.settings.execution_policy==='completion'?'Completion priority · automatic time and token budgets':'Fixed budgets'}</p><p>Search: {run.settings.search_enabled?'Enabled · automatic bounded queries':'Disabled'}</p>{['DRAFT','PAUSED'].includes(run.state)&&!run.closing_started&&<form onSubmit={e=>{e.preventDefault();execute(async()=>{setRun(await api(`/sessions/${run.id}/turn-limit`,{total:turnTotal,expected_revision:run.revision},'PATCH'))})}}><label>Total turns<input type="number" min={Math.max(4,run.turns.length+2+run.turns.length%2)} max="100" step="2" value={turnTotal} onChange={e=>setTurnTotal(+e.target.value)}/></label><button className="secondary" disabled={busy}>Update turn count</button><small>Completed turns stay. Two closings are reserved. Completion priority adjusts budgets automatically; fixed mode retains limits.</small></form>}</details>
   </aside></div>
   <div className="control-bar"><div className="controls-main">{['PAUSED','FAILED_RECOVERABLE','READY'].includes(run.state)&&run.settings.execution_policy!=='completion'&&<button className="primary" disabled={busy} onClick={()=>command('upgrade-resume')}>Upgrade and Resume</button>}{run.state==='DRAFT'&&(!preparing||run.preparation?.approval)&&<button className="primary" disabled={busy} onClick={()=>command('start')}><Play size={15}/> Start</button>}{['PREPARING','RUNNING','INGESTING','JUDGING'].includes(run.state)&&<button className="primary" disabled={busy} onClick={()=>command('pause')}><Pause size={15}/> Pause</button>}{['PAUSED','FAILED_RECOVERABLE','READY'].includes(run.state)&&<button className="primary" disabled={busy} onClick={()=>command('resume')}><Play size={15}/> {run.state==='FAILED_RECOVERABLE'?'Retry / Resume':'Resume'}</button>}<button className="secondary" disabled={busy||['PAUSING','STOPPING'].includes(run.state)} onClick={()=>command('restart')} title="Preserves this run and creates a fresh draft with the same pinned models"><RotateCcw size={15}/> Restart</button><button className="secondary" disabled={busy||(preparing&&!run.preparation?.approval)||terminal.includes(run.state)||run.state==='JUDGING'||['PAUSING','STOPPING'].includes(run.state)} onClick={()=>command('stop-and-judge')} title="Judge completed arguments and admitted evidence only"><Scale size={16}/> Stop & Judge</button><button className="quiet danger" disabled={busy||terminal.includes(run.state)} onClick={()=>command('cancel')}><Square size={13}/> Cancel</button></div><div className="controls-other"><a className="icon-button" title="Export Markdown" href={`/api/sessions/${run.id}/export?format=markdown`}><Download size={17}/><span>MD</span></a><a className="icon-button" title="Export JSON" href={`/api/sessions/${run.id}/export?format=json`}>JSON</a><button className="icon-button danger" disabled={busy||active.includes(run.state)} title="Delete session" onClick={remove}><Trash2 size={16}/></button></div></div>
  </main>}
  </div>{inspected&&run&&<SourceInspector source={inspected} runId={run.id} locator={locator} onClose={()=>setInspected(null)}/>}
 </div>
}
function Setup({defaults,models,busy,onBack,onCreate,onDefaults}:{defaults:Settings;models:any[];busy:boolean;onBack:()=>void;onCreate:(x:any)=>void;onDefaults:(x:Settings)=>void}){
 const [mode,setMode]=useState('guided');
 const [settings,setSettings]=useState<Settings>(structuredClone(defaults)),[proposition,setProposition]=useState(''),[alpha,setAlpha]=useState(''),[bravo,setBravo]=useState('');
 const set=(key:keyof Settings,value:any)=>setSettings(s=>({...s,[key]:value}));
 return <main className="setup"><button className="back-link" onClick={onBack}><ArrowLeft size={15}/> Sessions</button><div className="eyebrow">A NEW LINE OF INQUIRY</div><h1>What’s worth debating?</h1><p className="lead">Start with an idea or source material. Charlie helps you prepare a complete subject.</p><form onSubmit={e=>{e.preventDefault();onCreate({proposition,alpha_position:alpha,bravo_position:bravo,settings,preparation_mode:mode})}}><section className="form-section"><div className="form-section-title"><span>01</span><h2>The starting subject</h2></div><label>Preparation<select aria-label="Preparation" value={mode} onChange={e=>setMode(e.target.value)}><option value="guided">Prepare with Charlie</option><option value="prepared">I already have a prepared subject</option></select></label><p className="form-hint">You can leave the subject blank and add an image or document next.</p><label>State a proposition<textarea required={mode==='prepared'} minLength={mode==='prepared'?3:undefined} maxLength={4000} value={proposition} onChange={e=>setProposition(e.target.value)} placeholder="For example: Cities should make public transport free." rows={3}/></label><div className="two-columns"><label><span className="role-dot alpha"/>Alpha’s position<input value={alpha} onChange={e=>setAlpha(e.target.value)} placeholder="Support the proposition"/></label><label><span className="role-dot bravo"/>Bravo’s position<input value={bravo} onChange={e=>setBravo(e.target.value)} placeholder="Oppose the proposition"/></label></div></section>
 <section className="form-section"><div className="form-section-title"><span>02</span><h2>The participants</h2></div><p className="form-hint">Independent roles and histories. Charlie is pinned when preparation starts; other roles are pinned before debate.</p><div className="two-columns">{roles.map(role=><label key={role}>{role}<small>{role==='Charlie'?'Prepares shared evidence':role==='Judge'?'Evaluates completed arguments':'Debates an assigned position'}</small><select value={settings.models[role]} onChange={e=>set('models',{...settings.models,[role]:e.target.value})}>{!models.some(m=>m.name===settings.models[role])&&<option value={settings.models[role]}>{settings.models[role]} · availability unverified</option>}{models.map(m=><option key={m.name} value={m.name}>{m.name}</option>)}</select></label>)}</div><button type="button" className="text-button small" disabled={busy} onClick={()=>onDefaults(settings)}>Save these settings as defaults</button></section>
 <section className="form-section"><div className="form-section-title"><span>03</span><h2>Boundaries for the exchange</h2></div><label>Execution policy<select aria-label="Execution policy" value={settings.execution_policy??'fixed'} onChange={e=>set('execution_policy',e.target.value)}><option value="completion">Complete configured turns — automatic budgets</option><option value="fixed">Fixed time and token budgets</option></select><small>Completion priority preserves request deadlines and bounded retries. Waiting for your input still pauses the debate.</small></label><div className="two-columns"><label>Completed turns<input type="number" min="4" max="100" step="2" value={settings.turn_limit} onChange={e=>set('turn_limit',+e.target.value)}/><small>Two openings, paired rebuttals, two closings. Editable while paused until closings begin.</small></label><label>Active minutes<input type="number" min="1" max="240" disabled={settings.execution_policy==='completion'} value={settings.active_minutes} onChange={e=>set('active_minutes',+e.target.value)}/><small>{settings.execution_policy==='completion'?'Automatic in completion mode; each model attempt still has a ten-minute deadline.':'Loading and inference count. Waiting for you does not.'}</small></label></div><details className="advanced"><summary>Token allowances and context</summary><p className="form-hint">Completion priority grows token budgets as bounded work is admitted. Fixed mode can end before closings. Only verified context tiers are used.</p><div className="two-columns">{(['ingestion_tokens','debate_tokens','judgment_tokens','context_tokens','max_context_tokens','output_tokens'] as const).map(key=><label key={key}>{pretty(key)}<input type="number" min={key==='output_tokens'?128:key==='context_tokens'?2048:1024} max={key==='output_tokens'?16384:['context_tokens','max_context_tokens'].includes(key)?131072:10000000} disabled={settings.execution_policy==='completion'&&['ingestion_tokens','debate_tokens','judgment_tokens','output_tokens'].includes(key)} value={settings[key]??32768} onChange={e=>set(key,+e.target.value)}/></label>)}</div></details><label className="checkbox-label"><input type="checkbox" checked={settings.search_enabled} onChange={e=>set('search_enabled',e.target.checked)}/><span>Allow optional Ollama web search<small>Automatic bounded searches use Ollama’s hosted web-search service and require its API key. Queries leave this computer; debate models stay local and need no key.</small></span></label>{settings.search_enabled&&<label>Maximum search requests<input type="number" min="1" max="20" value={settings.search_limit} onChange={e=>set('search_limit',+e.target.value)}/></label>}</section><div className="setup-footer"><p>Next: combine inputs and review your debate brief.</p><button className="primary" disabled={busy}>Create debate <ArrowRight size={16}/></button></div></form></main>
}
function EvidenceForm({busy,add,preparing=false}:{preparing?:boolean;busy:boolean;add:(kind:string,body:any)=>Promise<boolean>}){
 const [mode,setMode]=useState('text'),[text,setText]=useState('');
 const [limits,setLimits]=useState({source_mib:25,pdf_pages:100,media_minutes:10,processing_seconds:180});
 useEffect(()=>{api('/health').then(h=>setLimits(h.limits)).catch(()=>{})},[]);
 return <div className="evidence-form"><h3>Add to the shared record</h3><div className="segmented"><button className={mode==='text'?'active':''} onClick={()=>setMode('text')}>Text</button><button className={mode==='file'?'active':''} onClick={()=>setMode('file')}>File</button><button className={mode==='url'?'active':''} onClick={()=>setMode('url')}>URL</button><button className={mode==='path'?'active':''} onClick={()=>setMode('path')}>Path</button></div>{mode==='file'?<label className="upload-label"><Upload size={20}/><span>Choose a source file</span><input type="file" accept={preparing?".txt,.md,.docx,.pdf,.png,.jpg,.jpeg,.webp":".txt,.md,.pdf,.png,.jpg,.jpeg,.webp,.wav,.mp3,.m4a,.ogg,.flac,.mp4,.mov,.webm"} disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(file){const f=new FormData();f.append('file',file);if(await add('',f))e.target.value=''}}}/></label>:<form onSubmit={async e=>{e.preventDefault();if(await add(mode,mode==='text'?{text}:mode==='path'?{path:text}:{url:text}))setText('')}}>{mode==='text'?<textarea aria-label="Evidence text" rows={4} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste source material…" required/>:<input aria-label={mode==='path'?'Local file path':'Public source URL'} type={mode==='path'?'text':'url'} value={text} onChange={e=>setText(e.target.value)} placeholder={mode==='path'?'/Users/you/Documents/evidence.pdf':'https://…'} required/>}<button className="secondary small" disabled={busy}>Add {mode==='text'?'text':mode==='path'?'path':'URL'} <Plus size={13}/></button></form>}<small className="limits-note">{limits.source_mib} MiB per source · {limits.pdf_pages} PDF pages · {limits.processing_seconds}s per extraction batch. {preparing?"Text, images, Markdown, DOCX and PDF. Local paths import a saved copy. Audio/video deferred.":`${limits.media_minutes} min media; local transcription required.`}</small></div>
}
function InstructionForm({busy,onAdd}:{busy:boolean;onAdd:(s:string)=>Promise<boolean>}){const [text,setText]=useState('');return <form onSubmit={async e=>{e.preventDefault();if(await onAdd(text))setText('')}}><textarea aria-label="Shared instructions" value={text} onChange={e=>setText(e.target.value)} rows={2} placeholder="Instructions for both sides…" required/><button className="text-button small" disabled={busy}>Add instructions <Plus size={12}/></button></form>}
function RequestPanel({request,busy,onAnswer}:{request:any;busy:boolean;onAnswer:(c:string,t:string)=>Promise<boolean>}){const [text,setText]=useState('');return <section className="request-panel"><div className="eyebrow">{request.role.toUpperCase()} HAS A QUESTION</div><h2>{request.question}</h2><p>{request.reason}</p><textarea value={text} onChange={e=>setText(e.target.value)} aria-label="Your answer" placeholder="Provide an answer, or add a source in the evidence panel."/><div><button className="primary" disabled={busy} onClick={()=>onAnswer('answer',text)}>Save answer</button><button className="secondary" disabled={busy} onClick={()=>onAnswer('decline','')}>Decline</button><button className="quiet" disabled={busy} onClick={()=>onAnswer('continue','')}>Continue without it</button></div>{request.source_id&&<small>Declining or continuing explicitly excludes this ambiguous source.</small>}</section>}
function VerdictPanel({verdict:v,onReference}:{verdict:any;onReference:(r:string)=>void}){return <section className="verdict"><div className="eyebrow"><Scale size={17}/> THE JUDGE’S ASSESSMENT</div><h2>{v.outcome}</h2><p className="verdict-reason">{v.justification}</p>{v.scores&&<div className="score-table"><div><span>Criterion</span><strong>Alpha</strong><strong>Bravo</strong></div>{['evidence','logic','relevance','engagement'].map(k=><div key={k}><span>{pretty(k)}</span><strong>{v.scores.Alpha[k]}<small> / 5</small></strong><strong>{v.scores.Bravo[k]}<small> / 5</small></strong></div>)}</div>}{['supported_claims','unsupported_claims','decisive_objections','concessions','limitations'].map(k=>v[k]?.length>0&&<div key={k}><h3>{pretty(k)}</h3><ul>{v[k].map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>)}<div className="citation-list">{v.references?.map((r:string)=><button key={r} onClick={()=>onReference(r)}>{r}</button>)}</div><p className="form-hint">Scores explain a model assessment. They are not probabilities or proof of correctness.</p></section>}
function SourceInspector({source:s,runId,locator,onClose}:{source:Source;runId:string;locator:any;onClose:()=>void}){
 const media=useRef<HTMLMediaElement>(null),dialog=useRef<HTMLDialogElement>(null);const url=`/api/sessions/${runId}/sources/${s.id}/original`;
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);
 useEffect(()=>{if(media.current&&locator?.start!=null)media.current.currentTime=locator.start},[locator]);
 return <dialog ref={dialog} className="source-dialog" onCancel={onClose}><div className="dialog-heading"><div><span className="eyebrow">SOURCE INSPECTOR · {s.id}</span><h2>{s.name}</h2></div><button className="icon-button" aria-label="Close source inspector" onClick={onClose}><X size={20}/></button></div><div className="dialog-body"><span className="status">{s.status}</span><a className="text-button" href={url+(s.kind==='pdf'&&locator?.page?'#page='+locator.page:'')} target="_blank" rel="noreferrer">Open original {s.kind==='pdf'&&locator?.page?`· page ${locator.page}`:''}<ExternalLink size={14}/></a>{['png','jpg','jpeg','webp'].includes(s.kind)&&<img className="source-image" src={url} alt="Original supplied evidence"/>}{['mp4','mov','webm'].includes(s.kind)&&<video ref={media as any} controls src={url} onLoadedMetadata={()=>{if(media.current&&locator?.start!=null)media.current.currentTime=locator.start}}/>}{['wav','mp3','m4a','ogg','flac'].includes(s.kind)&&<audio ref={media as any} controls src={url} onLoadedMetadata={()=>{if(media.current&&locator?.start!=null)media.current.currentTime=locator.start}}/>}{locator?.image_file&&<img className="source-image" src={`/api/sessions/${runId}/sources/${s.id}/images/${locator.image_file}`} alt="Extracted page or sampled frame"/>}<h3>Charlie’s interpretation</h3><p className="source-summary">{s.summary||'Not processed yet.'}</p>{s.uncertainty.length>0&&<div className="uncertainty"><strong>Uncertainty & processing limits</strong><ul>{s.uncertainty.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}<h3>Extracted passages</h3>{s.passages.map(p=><div className="passage" key={p.id}><strong>{p.id}</strong><span>{p.derived?'Derived observation':'Extracted source content'} · {JSON.stringify(p.locator)}</span><p>{p.text}</p>{p.locator.start!=null&&<button className="text-button small" onClick={()=>{if(media.current){media.current.currentTime=p.locator.start;media.current.play()}}}>Seek to {Math.floor(p.locator.start)}s</button>}{p.locator.page&&s.kind==='pdf'&&<a className="text-button small" href={url+'#page='+p.locator.page} target="_blank">Open page {p.locator.page}</a>}</div>)}<details><summary>Provenance</summary><p>SHA-256: {s.hash}</p><pre>{JSON.stringify(s.metadata,null,2)}</pre></details></div></dialog>
}
createRoot(document.getElementById('root')!).render(<App/>);
